plugins:
  ubiquity-os-marketplace/command-start-stop@demo:
    skipBotEvents: false
  ubiquity-os/command-demo@demo: null
  ubiquity-os-marketplace/command-wallet@demo: null
  ubiquity-os-marketplace/command-query@demo: null
  ubiquity-os-marketplace/text-conversation-rewards@v1.7.9:
    skipBotEvents: false
    with:
      incentives:
        collaboratorOnlyPaymentInvocation: false
        contentEvaluator:
          openAi:
            endpoint: "https://openrouter.ai/api/v1"
            model: "deepseek/deepseek-r1-0528:free"
        userExtractor: {}
        dataPurge: {}
        formattingEvaluator: {}
        payment: {}
        githubComment: {}
        reviewIncentivizer: {}
        simplificationIncentivizer: {}
        externalContent:
          llmImageModel:
            model: "meta-llama/llama-4-maverick:free"
          llmWebsiteModel:
            model: "deepseek/deepseek-r1-0528:free"
      payment:
        automaticTransferMode: false
      rewards:
        erc20RewardToken: "0x4F35e5C4D233f0cA201B3FFc006c29f6CefD1Fe7"
        evmPrivateEncrypted: "tJhJD2scM2fiKo0ww3UvwSmJoPau21qTAS2COmRs5ke_iO3oWeTMl0RRPOcjqxeiUOD68J4TKYnlVZCVyrmUpPKt-UFRefpo5FcumztY26y5eXmY1iTQqBx5Hr_KhmS_McOfSd566_iOhFaOWbH_z4Nrvwy6KOTQUANhUQsiABiM--2seQ"
        evmNetworkId: 100
  ubiquity-os-marketplace/daemon-disqualifier@v1.0.3: null
  ubiquity-os-marketplace/text-vector-embeddings@v1.1.1:
    with:
      demoFlag: true
